### ISSUE TITLE
Create Stream

### ISSUE THREAD

**Issue by aminosman** [vsouza/docker-Kinesis-local#5]
Is there a way to create a stream using some kind of config or env?

**Comment by vsouza** [comment]
@aminosman I put an example in README with a command to create streams.

`docker run -d -p 4567:4567 vsouza/kinesis-local --port 4567 --createStreaMs 5`

**Comment by aminosman** [comment]
@vsouza where in that command is the stream created and what is its name? I would like to reproduce this behavior using a config so I don't have to rely on code to create the stream 

`kinesis.createStream('some-stream-name')`
