### ISSUE TITLE
DockerFile for Kinesis KPL and KCL 

### ISSUE THREAD

**Issue by Anzani** [vsouza/docker-Kinesis-local#6]
Hi there,

I found this to be awesome and helpful. Do you have any plans to show how you can create and run Dockerfile for Kinesis KPL and KCL, this would also help.

I would like to create containers for my producers on EC2 instance, to ingest into my stream...similarly I would also like to try it for my consumers. any guidance would be much appreciated.

**Comment by vsouza** [comment]
@Anzani You could use the image as a dependency in your CI spec. It works like a database or cache layer. An example: https://docs.travis-ci.com/user/database-setup/
